import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./Navigation";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white">
        <div className="bg-spotlight" />
        <Navigation />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
